name: poc_movie
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  bloc: ^6.1.3
  rxdart: ^0.25.0
  eva_icons_flutter: ^2.0.1
  flutter_rating_bar: ^3.0.1+1
  font_awesome_flutter: ^8.12.0
  page_indicator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
